name: Build thesis

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_thesis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Compile Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: thesis.typ

      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          path: thesis.pdf
